### ISSUE TITLE
Cannot use latest openzeppelin-cli with an existing project.

### ISSUE THREAD

**Issue by hickscorp** [OpenZeppelin/openzeppelin-sdk#1135]
We're trying to upgrade to latest OZ tooling for a project that was using previous versions.

The first time, `oz` complained that the manifest was at a different version, and pointed us to documentation that didn't seem to be up to date. So we just deleted the `zos.json` file and ran `oz init` in our existing project.

The new `.openzeppelin/` folder structure was created, and after running `oz add` a bunch of times with each of our contract names, we tried running our deployment scripts.

```
[2019-07-19T20:17:09.661Z@NetworkController.js#_uploadSolidityLib] <started> Uploading AddressSet library
[2019-07-19T20:17:09.662Z@BaseSimpleProject.js#setImplementation] <started> Deploying logic contract for AddressSet
[2019-07-19T20:17:09.752Z@ErrorHandler.js#call] <started> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.basename (path.js:1289:5)
    at Object._log (/home/doodloo/.nvm/versions/node/v10.16.0/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/src/utils/Logger.ts:120:32)
    at Object.succeed (/home/doodloo/.nvm/versions/node/v10.16.0/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/src/utils/Logger.ts:97:10)
    at NetworkController.<anonymous> (/home/doodloo/.nvm/versions/node/v10.16.0/lib/node_modules/@openzeppelin/cli/src/models/network/NetworkController.ts:236:11)
    at Generator.next (<anonymous>)
    at fulfilled (/home/doodloo/.nvm/versions/node/v10.16.0/lib/node_modules/@openzeppelin/cli/lib/models/network/NetworkController.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-07-19T20:17:09.753Z@NetworkFile.js#write] <started> Created .openzeppelin/dev-5777.json
```

Happily, we were running this against Ganache - I'm glad, as a library has actually been deployed (and therefore we would have paid for gas).

Where is the update procedure to use the latest `oz` binary?
Would the old `.zos.dev-NETID.json` files be compatible with the new version - if we move and rename them inside the new `.openzeppelin/` folder?

Do we need to run anything like `oz link...` against `openzeppelin-solidity` and / or `@openzeppelin/upgrades`? Is there documentation available?

**Comment by spalladino** [comment]
Hey @hickscorp! The new naming and folder structure is yet to be released, we'll post more info about it on Monday! And yes, we had hit this error during our tests, but it is fixed in the version that will be published.

**Comment by hickscorp** [comment]
Thanks for spending time to answer @spalladino. I'm looking forward to reading the documentation on Monday!

**Comment by hickscorp** [comment]
@spalladino Hi there! Was there any further development for the documentation you mentioned?

**Comment by spalladino** [comment]
@hickscorp sure, the changes are listed in the [changelog](https://github.com/OpenZeppelin/openzeppelin-sdk/releases/tag/v2.5.0) for the 2.5 release. And the rename you are interested in is the one corresponding to https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1040.
