### ISSUE TITLE
Not working on Windows10

### ISSUE THREAD

**Issue by KimiWu123** [OpenZeppelin/openzeppelin-sdk#1223]
It's similar issue with #252. 
But, running as admin is not working for me. I got the same error message,
(Got the same error with Windows shell and Git bash)
I tried these two commands, and got the same result
``` 
npm install --global zos
npm install --global @openzeppelin/cli
```

```
>npm install --global @openzeppelin/cli
npm WARN deprecated truffle-config@1.1.16: WARNING: This package has been renamed to @truffle/config.
npm WARN deprecated truffle-provider@0.1.16: WARNING: This package has been renamed to @truffle/provider.
npm WARN deprecated truffle-error@0.0.5: WARNING: This package has been renamed to @truffle/error.
npm WARN deprecated truffle-interface-adapter@0.2.5: WARNING: This package has been renamed to @truffle/interface-adapter.
C:\Users\user\AppData\Roaming\npm\openzeppelin -> C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\lib\bin\oz-cli.js
C:\Users\user\AppData\Roaming\npm\zos -> C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\lib\bin\oz-cli.js
C:\Users\user\AppData\Roaming\npm\oz -> C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\lib\bin\oz-cli.js

> keccak@1.4.0 install C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\node_modules\keccak
> node-gyp rebuild


C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\node_modules\keccak
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-09-09T03_05_16_436Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.7.1 install C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.7.1 rebuild C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\node_modules\secp256k1
> node-gyp rebuild


C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\node_modules\secp256k1
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-09-09T03_05_17_889Z-debug.log
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> sha3@1.2.3 install C:\Users\user\AppData\Roaming\npm\node_modules\@openzeppelin\cli\node_modules\sha3
> node-gyp rebuild
```
Switch to python2 doesn't help, got another errors...

**Comment by jcarpanelli** [comment]
Hello @KimiWu123! I remember struggling with this same problem in the past, and I think I fixed it installing the [windows build tools](https://www.npmjs.com/package/windows-build-tools) using npm as administrator:
```
npm install --global windows-build-tools
```

Let me know if this is useful for you, as we are planning to prepare a setup guide for windows users!

**Comment by abcoathup** [comment]
Hi @KimiWu123,

You may want to consider using Windows Subsystem for Linux (I use this on Windows 10) rather than developing in Windows.  

David Burela's blog recommends using WSL and has instructions on how to setup:
https://davidburela.wordpress.com/2017/05/12/how-to-install-truffle-testrpc-on-ubuntu-or-windows-10-with-windows-subsystem-for-linux/

**Comment by KimiWu123** [comment]
Hi @jcarpanelli ,
It works! Than you! You could put the instruction in the document first. 

Hi @abcoathup ,
It's a good suggestion. I always have some trouble with working on Windows. I'll try it!
