### ISSUE TITLE
(@openzeppelin/upgrades) getFromLocal cannot find module

### ISSUE THREAD

**Issue by mortimr** [OpenZeppelin/openzeppelin-sdk#1246]
Hi,

I'm having an issue with `@openzeppelin/upgrades`:`2.5.3`. I'm currently trying the example use case from [here](https://docs.openzeppelin.com/sdk/2.5/zos-lib) and I have an issue when running tests. It looks like the migration starts before the contract build is complete, I'm getting the following error:

```
Error: Error: Error: Cannot find module '/repo/contracts/contracts_modules/metamarketplace/build/contracts/PlaceHolder_v0.json'
    at Object.run (/node_modules/truffle/build/webpack:/packages/migrate/index.js:96:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.37 (core: 5.0.37)
Node v10.16.2
```

When I run `truffle compile` before running the tests, everything works fine, but if I try running it fresh I get this error. This is my migration:

```
// Required by @openzeppelin/upgrades when running from truffle
global.artifacts = artifacts;
global.web3 = web3;

// Import dependencies from OpenZeppelin SDK programmatic library
const { Contracts, SimpleProject, ZWeb3 } = require('@openzeppelin/upgrades');

module.exports = async function(deployer) {

    ZWeb3.initialize(web3.currentProvider);

    const PlaceHolder_v0 = Contracts.getFromLocal('PlaceHolder_v0');
    const PlaceHolder_v1 = Contracts.getFromLocal('PlaceHolder_v1');

    /* Retrieve a couple of addresses to interact with the contracts. */
    const [creatorAddress, initializerAddress] = await ZWeb3.accounts();

    /* Create a SimpleProject to interact with OpenZeppelin programmatically. */
    const myProject = new SimpleProject('MyProject', null, { from: creatorAddress });

    const instance = await myProject.createProxy(PlaceHolder_v0, { initArgs: [42] });
    console.log('Contract\'s storage value:', (await instance.methods.value().call({ from: initializerAddress })).toString());

    await myProject.upgradeProxy(instance.address, PlaceHolder_v1, { initMethod: 'add', initArgs: [1] });
    console.log('Contract\'s storage new value:', (await instance.methods.value().call({ from: initializerAddress })).toString());
};
```

An idea from where it could come from ?

Thanks.

**Comment by mortimr** [comment]
Ok, it seems truffle does not create any build directory when running tests. But the global `artifacts` is still able to recover the build artifacts, meaning they are injected into the variable but not into the filesystem.

Is it possible to add a method on the `Contracts` class to build a `Contract` from a truffle `artifact` variable and not from a filesystem artifact ? My work-around is currently this:

``` javascript
// Required by @openzeppelin/upgrades when running from truffle
global.artifacts = artifacts;
global.web3 = web3;

// Import dependencies from OpenZeppelin SDK programmatic library
const { Contracts, SimpleProject, ZWeb3 } = require('@openzeppelin/upgrades');
const fs = require('fs-extra');

module.exports = async function(deployer) {

    ZWeb3.initialize(web3.currentProvider);

    const extra_build_dir = `${__dirname}/../zos_build/contracts`;

    if (fs.existsSync(extra_build_dir)) {
        fs.removeSync(extra_build_dir)
    }

    fs.ensureDirSync(extra_build_dir);
    fs.writeFileSync(`${extra_build_dir}/PlaceHolder_v0.json`, JSON.stringify(artifacts.require('PlaceHolder_v0')));
    fs.writeFileSync(`${extra_build_dir}/PlaceHolder_v1.json`, JSON.stringify(artifacts.require('PlaceHolder_v1')));
    fs.writeFileSync(`${extra_build_dir}/Initializable.json`, JSON.stringify(artifacts.require('Initializable')));

    Contracts.setLocalBuildDir(extra_build_dir);

    const PlaceHolder_v0 = Contracts.getFromLocal('PlaceHolder_v0');
    const PlaceHolder_v1 = Contracts.getFromLocal('PlaceHolder_v1');

    fs.removeSync(extra_build_dir);

    /* Retrieve a couple of addresses to interact with the contracts. */
    const [creatorAddress, initializerAddress] = await ZWeb3.accounts();

    /* Create a SimpleProject to interact with OpenZeppelin programmatically. */
    const myProject = new SimpleProject('MyProject', null, { from: creatorAddress });

    const instance = await myProject.createProxy(PlaceHolder_v0, { initArgs: [42] });
    console.log('Contract\'s storage value:', (await instance.methods.value().call({ from: initializerAddress })).toString());

    await myProject.upgradeProxy(instance.address, PlaceHolder_v1, { initMethod: 'add', initArgs: [1] });
    console.log('Contract\'s storage new value:', (await instance.methods.value().call({ from: initializerAddress })).toString());

};
```

But it feels dirty, what do you think about doing it this way ?

``` javascript
// Required by @openzeppelin/upgrades when running from truffle
global.artifacts = artifacts;
global.web3 = web3;

// Import dependencies from OpenZeppelin SDK programmatic library
const { Contracts, SimpleProject, ZWeb3 } = require('@openzeppelin/upgrades');
const fs = require('fs-extra');

module.exports = async function(deployer) {

    ZWeb3.initialize(web3.currentProvider);

    const PlaceHolder_v0 = Contracts.getFromArtifact(artifacts.require('PlaceHolder_v0'));
    const PlaceHolder_v1 = Contracts.getFromArtifact(artifacts.require('PlaceHolder_v1'));

    /* Retrieve a couple of addresses to interact with the contracts. */
    const [creatorAddress, initializerAddress] = await ZWeb3.accounts();

    /* Create a SimpleProject to interact with OpenZeppelin programmatically. */
    const myProject = new SimpleProject('MyProject', null, { from: creatorAddress });

    const instance = await myProject.createProxy(PlaceHolder_v0, { initArgs: [42] });
    console.log('Contract\'s storage value:', (await instance.methods.value().call({ from: initializerAddress })).toString());

    await myProject.upgradeProxy(instance.address, PlaceHolder_v1, { initMethod: 'add', initArgs: [1] });
    console.log('Contract\'s storage new value:', (await instance.methods.value().call({ from: initializerAddress })).toString());

};
```

I could help implementing this new method if needed !

**Comment by abcoathup** [comment]
Discussion in the Community Forum: https://forum.openzeppelin.com/t/proper-truffle-integration/1553
