### ISSUE TITLE
npm install leads to "Maybe git-submodule is broken?"

### ISSUE THREAD

**Issue by RubensGitHub** [OpenZeppelin/openzeppelin-sdk#1262]
I have no idea why Im getting this error. Its my first time working with zeppelin-cli.
The path to the git.exe is correct. I would highly appreciate some help :)

`1281 silly fetchPackageMetaData error for websocket@github:web3-js/WebSocket-Node#polyfill/globalThis Command failed: D:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
1281 silly fetchPackageMetaData fatal: 'submodule' appears to be a git command, but we were not
1281 silly fetchPackageMetaData able to execute it. Maybe git-submodule is broken?
1282 timing stage:rollbackFailedOptional Completed in 1ms
1283 timing stage:runTopLevelLifecycles Completed in 19450ms
1284 verbose stack Error: Command failed: D:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
1284 verbose stack fatal: 'submodule' appears to be a git command, but we were not
1284 verbose stack able to execute it. Maybe git-submodule is broken?
1284 verbose stack
1284 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
1284 verbose stack     at ChildProcess.emit (events.js:189:13)
1284 verbose stack     at maybeClose (internal/child_process.js:978:16)
1284 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
1285 verbose cwd D:\
1286 verbose Windows_NT 10.0.18362
1287 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@openzeppelin/cli"
1288 verbose node v11.4.0
1289 verbose npm  v6.4.1
1290 error code 128
1291 error Command failed: D:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
1291 error fatal: 'submodule' appears to be a git command, but we were not
1291 error able to execute it. Maybe git-submodule is broken?
1292 verbose exit [ 1, true ]`

**Comment by abcoathup** [comment]
Hi @RubensGitHub,

Unfortunately this appears to be an issue with your development environment setup.  

I have been searching on the web for the error message you are seeing.  
The best match appears to be https://github.com/npm/npm/issues/20815 

You could try updating the version of npm to 6.12.0 as the underlying referenced issue (https://github.com/npm/npm-lifecycle/pull/17) is apparently fixed. https://github.com/npm/cli/releases/tag/v6.12.0

On Windows, I use Windows Subsystem for Linux running Ubuntu and would recommend checking it out as I have much fewer issues that when I did smart contract development directly on Windows: https://docs.microsoft.com/en-us/windows/wsl/install-win10 

I suggest posting support questions like this in the OpenZeppelin Community Forum so that anyone from the community can help: https://forum.openzeppelin.com/

**Comment by spalladino** [comment]
Closing due to inactivity
