### ISSUE TITLE
`npm run test` fails on `packages/cli`

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#1268]
Testing fails on `packages/cli`

Reported in the community forum: https://forum.openzeppelin.com/t/cant-run-npm-run-test-on-package-cli/1627

---

Following setup instructions in https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/CONTRIBUTING.md
```
npm install
npx lerna bootstrap
openzeppelin-sdk/packages/cli$ npm link
openzeppelin-sdk/packages/lib$ npm link
```
When running tests:
```
openzeppelin-sdk/packages/cli$ npm test
```
They fail with following error:
```
$ npm run test

> @openzeppelin/cli@2.5.3 test /mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli
> ./scripts/test.sh

Starting our own ganache instance
Ganache CLI v6.3.0 (ganache-core: 2.4.0)
Error: Could not find @openzeppelin/upgrades/contracts/mocks/StorageMocksForComparison.sol from any sources; imported from /mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/contracts/mocks/Imports.sol
    at /mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:76:1
    at /mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/~/async/internal/onlyOnce.js:12:1
    at next (/mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/~/async/whilst.js:68:1)
    at /mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:64:1
    at /mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/packages/truffle-resolver/fs.js:85:1
    at /mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/~/async/internal/once.js:12:1
    at replenish (/mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/~/async/internal/eachOfLimit.js:61:1)
    at iterateeCallback (/mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/~/async/internal/eachOfLimit.js:50:1)
    at /mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/~/async/internal/onlyOnce.js:12:1
    at ReadFileContext.callback (/mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/node_modules/truffle/build/webpack:/packages/truffle-resolver/fs.js:81:1)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
Truffle v5.0.5 (core: 5.0.5)
Node v10.16.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @openzeppelin/cli@2.5.3 test: `./scripts/test.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @openzeppelin/cli@2.5.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abcoathup/.npm/_logs/2019-10-28T03_50_33_772Z-debug.log
```

**Comment by yxliang01** [comment]
@abcoathup Did you setup the dependency in the upper most level? i.e. at the root directory of this repo.

**Comment by abcoathup** [comment]
Hi @yxliang01,

I did the following, is there something I am missing?
>Following setup instructions in https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/CONTRIBUTING.md
>```
>npm install
>npx lerna bootstrap
>openzeppelin-sdk/packages/cli$ npm link
>openzeppelin-sdk/packages/lib$ npm link
>```

**Comment by yxliang01** [comment]
@abcoathup Can you try to go `openzeppelin-sdk/packages/lib` then do `npm run prepare` ?

**Comment by abcoathup** [comment]
Hi @yxliang01,

Thanks, I tried `npm run prepare` but got the same error.

**Comment by yxliang01** [comment]
Oh wait, I start realizing that it might be the case that the cli package is using the published version of that package while it might be possible that there's breaking changes not yet published. Thinking whether do `npm link @openzeppelin/upgrades` in the CLI package directory can solve this.

p.s. I'm not developer of this repo nor following closely, so I'm not so expert... :joy: We had successful run back then.

**Comment by abcoathup** [comment]
Hi @yxliang01,

Thank you.
```
npm link @openzeppelin/upgrades
```
Followed by
```
npx truffle compile 
```
Meant I could run most of the tests
```
npm run test
```

**Comment by yxliang01** [comment]
@abcoathup You are welcome. So, this is solved? Instead of doing `npx truffle compile` manually, I would suggest you to do `npm run prepare` though since this is more portable.

**Comment by spalladino** [comment]
Thanks for helping @yxliang01! FWIW, we are looking into [moving into yarn workspaces](https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1241), which seem to be more robust than plain lerna.

**Comment by abcoathup** [comment]
New steps:
In root directory run yarn
```
openzeppelin-sdk$ yarn
```
Then compile some contracts
```
openzeppelin-sdk/packages/cli$ npx truffle compile
```
Then run tests
```
openzeppelin-sdk/packages/cli$ yarn test
openzeppelin-sdk/packages/lib$ yarn test
```

**Comment by abcoathup** [comment]
Following test fails on a second and subsequent runs:
```
  link command
    1) should call link script with a list of dependencies and no install
```
With error:
```
Error: OpenZeppelin file .openzeppelin/project.json not found. Run 'openzeppelin init' first to initialize the project.
    at new LocalController (/mnt/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/src/models/local/LocalController.ts:32:13)
```
----
Also first run has had following:
```
  1) Contract: create script
       on published project
         "before each" hook: setup for "should refuse create a proxy for unlinked dependency":
     Error:
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 9555
    - network_id > 4447
```
```
  2) Contract: update script
       on dependency contract in unpublished mode
         updating on dependency
           "before each" hook: setup for "should upgrade the version of all proxies":
     Failed deployment of dependency mock-stdlib-undeployed with error:
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 9555
    - network_id > 4447
```

**Comment by spalladino** [comment]
Closing issue. Please reopen if it still happens
