### ISSUE TITLE
`make` failed with exit code: 2

### ISSUE THREAD

**Issue by abedshouman** [OpenZeppelin/openzeppelin-sdk#1280]
make: Leaving directory '/usr/local/lib/node_modules/zos/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/zos/node_modules/scrypt
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by spalladino** [comment]
Hey @abedshouman! I'm afraid this is not an error with the SDK itself, but with one of its transitive dependencies. Please check out [scrypt's installation instructions](https://www.npmjs.com/package/scrypt)!

**Comment by spalladino** [comment]
By the way, recent versions of the SDK use a more recent version of web3.js, which does not depend on scrypt. Have you tried installing `@openzeppelin/cli@2.5.3`? I see you are installing `zos`, which is an older version of the package.

**Comment by spalladino** [comment]
Closing due to inactivity
