### ISSUE TITLE
Install fails on make for sha3 with node 13.1.0

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#1289]
`npm install @openzeppelin/cli` fails with node 13.1.0.

Appears to be issue with `sha3@1.2.3` which is a dependency of `web3@1.2.2`

```
sha3.target.mk:113: recipe for target 'Release/obj.target/sha3/src/addon.o' failed
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/mnt/c/Users/andre/Documents/projects/forum/pkr/node_modules/sha3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/abcoathup/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/home/abcoathup/.nvm/versions/node/v13.1.0/bin/node" "/home/abcoathup/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/c/Users/andre/Documents/projects/forum/pkr/node_modules/sha3
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN pkr@1.0.0 No description
npm WARN pkr@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abcoathup/.npm/_logs/2019-11-21T06_26_59_440Z-debug.log
```

**Comment by spalladino** [comment]
Thanks for the report. This is being tracked on https://github.com/ethereum/web3.js/issues/3181.

**Comment by spalladino** [comment]
Working on 2.7.1
