### ISSUE TITLE
`oz init` fails with Error: Provider not set or invalid

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#1464]
I'm getting the following error when running `oz init` in an empty folder using `v2.8.0-rc.0`:

```
[2020-02-17T18:42:28.166Z@errors.js#call] <started> Error: Provider not set or invalid
    at Object.InvalidProvider (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/web3-core-helpers/src/errors.js:38:16)
    at RequestManager.send (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/web3-core-requestmanager/src/index.js:128:32)
    at sendRequest (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/web3-core-method/src/index.js:651:42)
    at Net.send [as getId] (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/web3-core-method/src/index.js:672:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js:112:34)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js:4:12)
    at Function.getNetwork (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js:111:16)
    at Function.<anonymous> (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js:117:43)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js:4:12)
    at Function.getNetworkName (/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js:116:16)
```

This also happens in a directory with an already bootstrapped project initialized project with truffle.

**Comment by frangio** [comment]
Thanks for reporting! This should be fixed in the latest release candidate.

`npm install @openzeppelin/cli@rc`
