### ISSUE TITLE
Zepkit: scrypt node_module_version compilation error

### ISSUE THREAD

**Issue by frederickalcantara** [OpenZeppelin/openzeppelin-sdk#817]
Anytime I try to add a contract with zos I get the following error: 

`
Error: The module '/usr/local/lib/node_modules/zos/node_modules/scrypt/build/Release/scrypt.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).
`

What do I need to do to solve this issue?

**Comment by ylv-io** [comment]
Hey @frederickalcantara. It seems your [scrypt](https://www.npmjs.com/package/scrypt) package was compiled against different Node.js version. Try to uninstall `zos` globally and install it again.

**Comment by spalladino** [comment]
Closing due to lack of activity

**Comment by JasoonS** [comment]
```
/home/jasoons/.fnm/node-versions/v12.16.0/installation/lib/node_modules/@openzeppelin/cli/node_modules/scrypt-shim/src/index.js:27
      throw e;
      ^

Error: The module '/home/jasoons/node_modules/scrypt/build/Release/scrypt.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1207:18)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/jasoons/node_modules/scrypt/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
```

I'm getting the following error. I've run `npm uninstall @openzeppelin/cli -g ` and then `npm install @openzeppelin/cli -g` and I still get the error. I'll switching back to node v10 worked.

**Comment by MajdT51** [comment]
I have the same issue on node v12.14.0
